version: "3"
services:
  app:
    container_name: dportfolio_
    # image: "nginx"
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - "8080:8080"
    networks:
      - frontend

    appFile:
      container_name: dportfolio

      build:
        context: .
        dockerfile: ./node.Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - "dportfolio_:/var/lib/mysql"
      links:
        - db
      networks:
        - backend
 volumes:
      - ./docker/data:/var/lib/postgresql/data
networks: # 가장 기본적인 bridge 네트워크
  frontend:
    driver: bridge
