name: PR Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps: 
         - name: yarn add
           run: yarn add
         - name: run test code
           run: yarn test
