name: PR Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: npm install
        run: npm install
      - name: run test code
        run: npm test
